-- MySQL Script generated by MySQL Workbench
-- Wed Dec  4 21:09:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema juego_cartas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `juego_cartas` ;

-- -----------------------------------------------------
-- Schema juego_cartas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `juego_cartas` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `juego_cartas` ;

-- -----------------------------------------------------
-- Table `juego_cartas`.`players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juego_cartas`.`players` ;

CREATE TABLE IF NOT EXISTS `juego_cartas`.`players` (
  `player_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `player_name` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `password` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`player_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `idx_player_id` (`player_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `juego_cartas`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juego_cartas`.`category` ;

CREATE TABLE IF NOT EXISTS `juego_cartas`.`category` (
  `category_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `category_description` VARCHAR(400) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `player_id` INT UNSIGNED NULL,
  PRIMARY KEY (`category_id`),
  INDEX `fk_category_players1_idx` (`player_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_players1`
    FOREIGN KEY (`player_id`)
    REFERENCES `juego_cartas`.`players` (`player_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `juego_cartas`.`cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juego_cartas`.`cards` ;

CREATE TABLE IF NOT EXISTS `juego_cartas`.`cards` (
  `card_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(300) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `type` ENUM('answer', 'question') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `category_id` INT UNSIGNED NOT NULL,
  `player_id` INT UNSIGNED NULL,
  PRIMARY KEY (`card_id`),
  INDEX `fk_Cards_Category` (`category_id` ASC) VISIBLE,
  INDEX `fk_cards_players1_idx` (`player_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cards_Category`
    FOREIGN KEY (`category_id`)
    REFERENCES `juego_cartas`.`category` (`category_id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_cards_players1`
    FOREIGN KEY (`player_id`)
    REFERENCES `juego_cartas`.`players` (`player_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
