-- MySQL Script generated by MySQL Workbench
-- Fri Nov 29 13:11:48 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema juego_cartas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `juego_cartas` ;

-- -----------------------------------------------------
-- Schema juego_cartas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `juego_cartas` ;
USE `juego_cartas` ;

-- -----------------------------------------------------
-- Table `juego_cartas`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juego_cartas`.`category` ;

CREATE TABLE IF NOT EXISTS `juego_cartas`.`category` (
  `category_id` INT UNSIGNED NOT NULL,
  `category_name` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `category_description` VARCHAR(400) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juego_cartas`.`cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juego_cartas`.`cards` ;

CREATE TABLE IF NOT EXISTS `juego_cartas`.`cards` (
  `card_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(300) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `type` ENUM('answer', 'question') COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `category_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`card_id`, `category_id`),
  INDEX `fk_Cards_Category` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cards_Category`
    FOREIGN KEY (`category_id`)
    REFERENCES `juego_cartas`.`category` (`category_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juego_cartas`.`players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juego_cartas`.`players` ;

CREATE TABLE IF NOT EXISTS `juego_cartas`.`players` (
  `player_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `player_name` VARCHAR(50) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(100) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `password` VARCHAR(50) COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `custom_categories` VARCHAR(100) NOT NULL,
  `custom_cards` ENUM("custom_answer", "custom_question") NOT NULL,
  INDEX `idx_player_id` (`player_id` ASC) VISIBLE,
  PRIMARY KEY (`player_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juego_cartas`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juego_cartas`.`game` ;

CREATE TABLE IF NOT EXISTS `juego_cartas`.`game` (
  `player_id` INT UNSIGNED NOT NULL,
  `card_id` INT UNSIGNED NOT NULL,
  `player_has_card` ENUM("yes", "no") NOT NULL,
  `total_players` INT NOT NULL,
  PRIMARY KEY (`player_id`, `card_id`),
  INDEX `idx_game` (`card_id` ASC) VISIBLE,
  CONSTRAINT `fk_Players_has_Cards_Cards1`
    FOREIGN KEY (`card_id`)
    REFERENCES `juego_cartas`.`cards` (`card_id`),
  CONSTRAINT `fk_Players_has_Cards_Players1`
    FOREIGN KEY (`player_id`)
    REFERENCES `juego_cartas`.`players` (`player_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
